apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dzkc0ira5-nodejs
  janus-idp.io/tekton: dzkc0ira5-nodejs
  backstage.io/kubernetes-id: dzkc0ira5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dzkc0ira5-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
