apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dzkc0ira5-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-cf8763a004.y8bz.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:5694e7afe7e4ace6e0363b5517de0473326537df@sha256:c1a0aca053abb2fbe232a12a367b4e9f068225cc456f660379e0722885aa4b02
          name: container-image
